version: '3.7'

services:

  sample:
    container_name: sample
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3005:3004
    environment:
      - CHOKIDAR_USEPOLLING=true
